# This file was generated by GoReleaser. DO NOT EDIT.
class Gopass < Formula
  desc "The slightly more awesome Standard Unix Password Manager for Teams."
  homepage "https://www.gopass.pw/"
  version "1.9.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gopasspw/gopass/releases/download/v1.9.2/gopass-1.9.2-darwin-amd64.tar.gz"
    sha256 "9fda4b6cf3b4d8c351af2fdc9412c366b5420f4b7dae455462b196be3b84129e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gopasspw/gopass/releases/download/v1.9.2/gopass-1.9.2-linux-amd64.tar.gz"
      sha256 "76ff3293ad2975ff4e378730501f2aa0a0e2da21908aa01e1397d707a4de26e1"
    end
  end
  
  depends_on "git"
  depends_on "gnupg"
  depends_on "terminal-notifier"

  def install
    ENV["GOPATH"] = buildpath
    (buildpath/"src/github.com/gopasspw/gopass").install buildpath.children
    
    cd "src/github.com/gopasspw/gopass" do
      ENV["PREFIX"] = prefix
      system "make", "install"
    end
    
    system bin/"gopass completion bash > bash_completion.bash"
    system bin/"gopass completion zsh > zsh_completion.zsh"
    bash_completion.install "bash_completion.bash"
    zsh_completion.install "zsh_completion.zsh"
  end

  def caveats; <<~EOS
    Gopass has been installed, have fun!
    If upgrading from `pass`, everything should work as expected.
    If installing from scratch, you need to either initialize a new repository now...
      gopass init
    ...or clone one from a source:
      gopass clone git@code.example.com:example/pass.git
    In order to use the great autocompletion features (they're helpful with gopass),
    please make sure you have autocompletion for homebrew enabled:
      https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
    More information:
      https://www.gopass.pw/
      https://github.com/gopasspw/gopass/README.md
  EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gopass version")
  end
end
