# This file was generated by GoReleaser. DO NOT EDIT.
class Gopass < Formula
  desc "The slightly more awesome Standard Unix Password Manager for Teams."
  homepage "https://www.gopass.pw/"
  version "1.10.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gopasspw/gopass/releases/download/v1.10.0/gopass-1.10.0-darwin-amd64.tar.gz"
    sha256 "fb06ffb784db930b50c522654f2f44e2d90d4b866d9f63f6a217c224c18aac22"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gopasspw/gopass/releases/download/v1.10.0/gopass-1.10.0-linux-amd64.tar.gz"
      sha256 "88bdba5ba5de857869ba0c668dcf9148cffe1983626b54394c0765362370a6be"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gopasspw/gopass/releases/download/v1.10.0/gopass-1.10.0-linux-arm64.tar.gz"
        sha256 "c4c38acc02dfa1ca32716fc2c0091fab800aa98fa64f1cb50ef9b85ff8cc750c"
      else
        url "https://github.com/gopasspw/gopass/releases/download/v1.10.0/gopass-1.10.0-linux-armv6.tar.gz"
        sha256 "0701f5c4d0efb1a369271aaff4ddceee7ad08fac2d1d22bbcac0b5220684074d"
      end
    end
  end
  
  depends_on "git"
  depends_on "gnupg"
  depends_on "terminal-notifier"

  def install
    ENV["GOPATH"] = buildpath
    (buildpath/"src/github.com/gopasspw/gopass").install buildpath.children
    
    cd "src/github.com/gopasspw/gopass" do
      ENV["PREFIX"] = prefix
      system "make", "install"
    end
    
    system bin/"gopass completion bash > bash_completion.bash"
    system bin/"gopass completion zsh > zsh_completion.zsh"
    bash_completion.install "bash_completion.bash"
    zsh_completion.install "zsh_completion.zsh"
  end

  def caveats; <<~EOS
    Gopass has been installed, have fun!
    If upgrading from `pass`, everything should work as expected.
    If installing from scratch, you need to either initialize a new repository now...
      gopass init
    ...or clone one from a source:
      gopass clone git@code.example.com:example/pass.git
    In order to use the great autocompletion features (they're helpful with gopass),
    please make sure you have autocompletion for homebrew enabled:
      https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
    More information:
      https://www.gopass.pw/
      https://github.com/gopasspw/gopass/README.md
  EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gopass version")
  end
end
