# This file was generated by GoReleaser. DO NOT EDIT.
class Gopass < Formula
  desc "The slightly more awesome Standard Unix Password Manager for Teams."
  homepage "https://www.gopass.pw/"
  version "1.9.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gopasspw/gopass/releases/download/v1.9.1/gopass-1.9.1-darwin-amd64.tar.gz"
    sha256 "07131e011b8655de4a194bc2fa957d245fb5aae3bbcb1e166e883a4ed36ed6f7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gopasspw/gopass/releases/download/v1.9.1/gopass-1.9.1-linux-amd64.tar.gz"
      sha256 "4a8dfdddc743267b1b2cda84c4b63cfc61a887deb580e2acc0314be1154859fb"
    end
  end
  
  depends_on "git"
  depends_on "gnupg"
  depends_on "terminal-notifier"

  def install
    ENV["GOPATH"] = buildpath
    (buildpath/"src/github.com/gopasspw/gopass").install buildpath.children
    
    cd "src/github.com/gopasspw/gopass" do
      ENV["PREFIX"] = prefix
      system "make", "install"
    end
    
    system bin/"gopass completion bash > bash_completion.bash"
    system bin/"gopass completion zsh > zsh_completion.zsh"
    bash_completion.install "bash_completion.bash"
    zsh_completion.install "zsh_completion.zsh"
  end

  def caveats; <<~EOS
    Gopass has been installed, have fun!
    If upgrading from `pass`, everything should work as expected.
    If installing from scratch, you need to either initialize a new repository now...
      gopass init
    ...or clone one from a source:
      gopass clone git@code.example.com:example/pass.git
    In order to use the great autocompletion features (they're helpful with gopass),
    please make sure you have autocompletion for homebrew enabled:
      https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
    More information:
      https://www.gopass.pw/
      https://github.com/gopasspw/gopass/README.md
  EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gopass version")
  end
end
